-- Insert the requested interest categories
insert into public.interest_categories (name, group_name, emoji, tagline) values
  ('Running', 'Sports & Fitness', '🏃', 'For those who love to hit the pavement'),
  ('Cycling', 'Sports & Fitness', '🚴', 'Pedal power and open roads'),
  ('Swimming', 'Sports & Fitness', '🏊', 'Making a splash in the pool or open water'),
  ('Tennis', 'Sports & Fitness', '🎾', 'Serve, volley, and rally'),
  ('Basketball', 'Sports & Fitness', '🏀', 'Hoops, layups, and team spirit'),
  ('Soccer', 'Sports & Fitness', '⚽', 'The beautiful game'),
  ('Yoga', 'Sports & Fitness', '🧘', 'Flexibility, balance, and mindfulness'),
  ('Weightlifting', 'Sports & Fitness', '🏋️', 'Pumping iron and getting stronger'),
  ('Rock Climbing', 'Sports & Fitness', '🧗', 'Scaling walls and conquering heights'),
  ('Martial Arts', 'Sports & Fitness', '🥋', 'Discipline, technique, and sparring'),
  ('Golf', 'Sports & Fitness', '⛳', 'Hitting the links for a relaxed round'),
  ('Volleyball', 'Sports & Fitness', '🏐', 'Spikes, sets, and sand'),
  
  ('Web Development', 'Tech & Science', '💻', 'Building the digital world'),
  ('Artificial Intelligence', 'Tech & Science', '🤖', 'Exploring the future of machine learning'),
  ('Cybersecurity', 'Tech & Science', '🔒', 'Defending the digital frontier'),
  ('Data Science', 'Tech & Science', '📊', 'Extracting insights from the noise'),
  ('Robotics', 'Tech & Science', '🦾', 'Building and programming autonomous machines'),
  ('Astronomy', 'Tech & Science', '🔭', 'Stargazing and cosmic curiosities'),
  ('Physics', 'Tech & Science', '⚛️', 'Understanding the fundamental laws of nature'),
  ('Startups', 'Tech & Science', '🚀', 'Building the next big thing from scratch'),
  ('Crypto & Web3', 'Tech & Science', '⛓️', 'Exploring decentralized technologies'),
  ('Open Source', 'Tech & Science', '🐧', 'Collaborating on free software'),
  ('Game Development', 'Tech & Science', '🕹️', 'Creating interactive digital worlds'),
  
  ('Painting', 'Arts & Culture', '🎨', 'Expressing creativity on canvas'),
  ('Photography', 'Arts & Culture', '📸', 'Capturing moments through the lens'),
  ('Creative Writing', 'Arts & Culture', '✍️', 'Penning stories, poems, and essays'),
  ('Live Music', 'Arts & Culture', '🎸', 'Rocking out at gigs and concerts'),
  ('Theater & Acting', 'Arts & Culture', '🎭', 'Taking the stage and performing'),
  ('Museums & Galleries', 'Arts & Culture', '🏛️', 'Appreciating history and fine art'),
  ('Architecture', 'Arts & Culture', '🏙️', 'Exploring structural design and cityscapes'),
  ('Film & Cinema', 'Arts & Culture', '🎬', 'For lovers of the silver screen'),
  ('Fashion & Design', 'Arts & Culture', '👗', 'Following trends and creating styles'),
  ('Pottery & Ceramics', 'Arts & Culture', '🏺', 'Molding clay into beautiful shapes'),
  ('Dance', 'Arts & Culture', '💃', 'Moving to the rhythm and beat'),
  
  ('Coffee Socials', 'Social & Nightlife', '☕', 'Chatting over a warm brew'),
  ('Pub Crawls', 'Social & Nightlife', '🍻', 'Discovering local bars and brews'),
  ('Clubbing', 'Social & Nightlife', '🪩', 'Dancing the night away'),
  ('Language Exchange', 'Social & Nightlife', '🌍', 'Practicing new languages with locals'),
  ('Trivia Nights', 'Social & Nightlife', '🧠', 'Testing your general knowledge'),
  ('Karaoke', 'Social & Nightlife', '🎤', 'Singing your heart out'),
  ('Networking', 'Social & Nightlife', '🤝', 'Making professional connections'),
  ('Comedy Clubs', 'Social & Nightlife', '😂', 'Enjoying stand-up and improv'),
  ('Live Podcasts', 'Social & Nightlife', '🎙️', 'Attending live recordings and talks'),
  ('Speed Dating', 'Social & Nightlife', '💘', 'Meeting singles in a fast-paced environment'),
  ('Mixology', 'Social & Nightlife', '🍸', 'Crafting and tasting cocktails'),
  
  ('Hiking', 'Outdoors & Adventure', '🥾', 'Exploring nature trails and peaks'),
  ('Camping', 'Outdoors & Adventure', '⛺', 'Sleeping under the stars'),
  ('Surfing', 'Outdoors & Adventure', '🏄', 'Catching waves and ocean vibes'),
  ('Skiing & Snowboarding', 'Outdoors & Adventure', '🏂', 'Hitting the snowy slopes'),
  ('Scuba Diving', 'Outdoors & Adventure', '🤿', 'Exploring underwater worlds'),
  ('Kayaking', 'Outdoors & Adventure', '🛶', 'Paddling through rivers and lakes'),
  ('Birdwatching', 'Outdoors & Adventure', '🦅', 'Spotting local and rare birds'),
  ('Fishing', 'Outdoors & Adventure', '🎣', 'Relaxing by the water with a rod'),
  ('Mountain Biking', 'Outdoors & Adventure', '🚵', 'Riding rugged off-road trails'),
  ('Sailing', 'Outdoors & Adventure', '⛵', 'Navigating the open waters'),
  
  ('Board Games', 'Games & Hobbies', '🎲', 'Strategic tabletop fun'),
  ('Video Gaming', 'Games & Hobbies', '🎮', 'Console, PC, and competitive gaming'),
  ('Chess', 'Games & Hobbies', '♟️', 'For sharp minds who love strategy'),
  ('Dungeons & Dragons', 'Games & Hobbies', '🐉', 'Roleplaying in fantasy realms'),
  ('Magic: The Gathering', 'Games & Hobbies', '🃏', 'Deck building and card battles'),
  ('Knitting & Crochet', 'Games & Hobbies', '🧶', 'Crafting cozy textiles'),
  ('Gardening', 'Games & Hobbies', '🌱', 'Cultivating plants and flowers'),
  ('DIY & Woodworking', 'Games & Hobbies', '🔨', 'Building and fixing things by hand'),
  ('Baking', 'Games & Hobbies', '🧁', 'Whipping up sweet treats'),
  ('Model Building', 'Games & Hobbies', '🚂', 'Assembling miniatures and dioramas'),
  
  ('Fine Dining', 'Food & Drink', '🍽️', 'Experiencing high-end gastronomy'),
  ('Street Food', 'Food & Drink', '🌮', 'Tasting local flavors on the go'),
  ('Wine Tasting', 'Food & Drink', '🍷', 'Swirling, sniffing, and sipping'),
  ('Craft Beer', 'Food & Drink', '🍺', 'Exploring microbreweries and ales'),
  ('Vegan Cooking', 'Food & Drink', '🥗', 'Plant-based culinary adventures'),
  ('BBQ & Grilling', 'Food & Drink', '🥩', 'Mastering the art of smoked meats'),
  ('Sushi Making', 'Food & Drink', '🍣', 'Rolling your own maki and nigiri'),
  ('Baking Bread', 'Food & Drink', '🥖', 'Perfecting the sourdough starter'),
  ('Food Photography', 'Food & Drink', '📷', 'Capturing delicious meals beautifully'),
  
  ('Meditation', 'Wellness & Lifestyle', '🧘‍♂️', 'Finding inner peace and focus'),
  ('Reading & Book Clubs', 'Wellness & Lifestyle', '📚', 'Discussing literature with others'),
  ('Minimalism', 'Wellness & Lifestyle', '✨', 'Living simply and intentionally'),
  ('Astrology', 'Wellness & Lifestyle', '⭐', 'Exploring zodiac signs and charts'),
  ('Volunteering', 'Wellness & Lifestyle', '🤲', 'Giving back to the community'),
  ('Personal Finance', 'Wellness & Lifestyle', '💰', 'Managing money and investing'),
  ('Self-Improvement', 'Wellness & Lifestyle', '📈', 'Working on personal growth'),
  ('Journaling', 'Wellness & Lifestyle', '📔', 'Reflecting through daily writing'),
  ('Sustainable Living', 'Wellness & Lifestyle', '♻️', 'Adopting eco-friendly habits')
on conflict (name) do update set group_name = excluded.group_name, emoji = excluded.emoji, tagline = excluded.tagline;
